project_id = "qjacgxvzjfjxytfggqro"

[functions.check-expired-trials]
verify_jwt = false

[functions.cleanup-grace-period-images]
verify_jwt = false

[functions.send-grace-period-notifications]
verify_jwt = false

[functions.handle-stripe-webhook]
verify_jwt = false